site_name: S3rius' Dev Notes
repo_name: s3rius/obsidian
repo_url: https://github.com/s3rius/obsidian
use_directory_urls: true

edit_uri: ''

theme:
  name: material
  features:
    - search.suggest

plugins:
  - search
  - i18n:
      default_language: ru
      languages:
        en: english
        ru: Ñ€ÑƒÑÑĞºĞ¸Ğ¹

extra:
    alternate:
    - name: ğŸ‡·ğŸ‡º Ğ ÑƒÑÑĞºĞ¸Ğ¹
      link: /ru/
      lang: ru

    - name: ğŸ‡¬ğŸ‡§ English
      link: /en/
      lang: en

