site_name: S3rius' Dev Notes
repo_name: s3rius/obsidian
repo_url: https://github.com/s3rius/obsidian
use_directory_urls: true

edit_uri: ''

theme:
  name: material
  features:
    - search.suggest
    - navigation.tabs

markdown_extensions:
  - fenced_code
  - codehilite:
      use_pygments: false
      linenums: true
  - termynal
  - admonition
  - extra
  - pymdownx.tabbed
  - toc:
      permalink: true
  - markdown_include.include:
      base_path: docs

plugins:
  - search
  - termynal
  - translations: # https://github.com/s3rius/mkdocs-translations
      default_language: ru
      languages:
        en: english
        ru: Ñ€ÑƒÑÑĞºĞ¸Ğ¹

extra:
    alternate:
    - name: ğŸ‡·ğŸ‡º Ğ ÑƒÑÑĞºĞ¸Ğ¹
      link: /ru/
      lang: ru

    - name: ğŸ‡¬ğŸ‡§ English
      link: /en/
      lang: en

extra_css:
  - css/highlight_style.css

extra_javascript:
  - js/highlight.min.js
  - js/startup.js
